set nocompatible              " be iMproved, required
set nomodeline
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'junegunn/goyo.vim'

Plugin 'miyakogi/conoline.vim'

Plugin 'tpope/vim-fugitive'

"Plugin 'godlygeek/tabular'

"Plugin 'plasticboy/vim-markdown'

Plugin 'mattn/emmet-vim'

"Plugin 'Gavinok/vim-troff'

"Plugin 'cloudhead/shady.vim'

call vundle#end()            " required
filetype plugin indent on    " required

set nowrap
set ruler
"set laststatus=2
set list
set listchars=
set listchars+=precedes:<,extends:>
set listchars+=tab:⇥\ 
set sidescroll=5
set scrolloff=5
set cc=80
set title
colorscheme elflord
syntax on
